version: '2.1'
services:

  mongo:
    image: mongo:2.6.11
    ports:
     - "27017:27017"
  application:
    build: .
    command:  npm start
    ports:
     - "8080:8080"
    volumes :
    - ./:/app
    links:
     - mongo


