version: '2.1'
services:
  shorty:
    build: .
    # command: npm start
    ports:
      - 8080:8080
    links:
      - mongo
    depends_on:
      - mongo
    command: npm start
  mongo:
    image: mongo